name: health-simulator
namespace: default

deployment:
  env:
    SERVER_SERVLET_CONTEXT_PATH: /health-simulator
  image: health-simulator
  # not recommended for production
  pullPolicy: Never
  updateStrategy: RollingUpdate
  maxSurge: 100%
  maxUnavailable: 0%
  replicas: 1
  restartPolicy: Always
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
