apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    spring-boot: "true"
  # Filter discovery to tagged services
  annotations:
    spring-boot-admin: "true"
spec:
  ports:
    - port: {{ .Values.deployment.server.port }}
      targetPort: http
      protocol: TCP
      # Name must be http or https
      # Alternative: configure spring.cloud.kubernetes.discovery.primary-port-name
      name: http
    - port: {{ .Values.deployment.management.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app: {{ .Values.name }}
