name: spring-boot-app-default
namespace: default

deployment:
  image: spring-boot-app-default
  pullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  maxSurge: 100%
  maxUnavailable: 0%
  replicas: 2
  restartPolicy: Always
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
