name: spring-boot-app-default
namespace: default

deployment:
  env:
    SERVER_SERVLET_CONTEXT_PATH: /app
  image: spring-boot-app-default
  # not recommended for production
  pullPolicy: Never
  updateStrategy: RollingUpdate
  maxSurge: 100%
  maxUnavailable: 0%
  replicas: 2
  restartPolicy: Always
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
