name: spring-boot-admin
namespace: default
serviceAccountName: spring-boot-admin-account

deployment:
  env:
    SPRING_BOOT_ADMIN_UI_TITLE: Spring Boot Admin - Kubernetes
  image: spring-boot-admin
  pullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  maxSurge: 100%
  maxUnavailable: 0%
  replicas: 2
  restartPolicy: Always
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
